version: 2
jobs:
  build:
    working_directory: /go/src/github.com/fbonhomm/Simple-LZSS
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: install module
          command: 'go mod download'
      - run:
          name: linter
          command: '/go/bin/golangci-lint run ./source'
      - run:
          name: test
          command: 'go test -v ./test'

